#ifndef _ERROR_H_STRUCTBOT
#define _ERROR_H_STRUCTBOT

//Definitions for errors structbot can have
#define STRUCTBOT_ERR_NONE 0
#define STRUCTBOT_ERR_PQOUTOFMEM 1
#define STRUCTBOT_ERR_PQADDNOREALLOC 2
#define STRUCTBOT_ERR_REASPERMERROR  3
#define STRUCTBOT_ERR_REASUNKTYP 4

#endif //_ERROR_H_STRUCTBOT
